# site settings
title: Blanc Nacarat.
name: Blanc nacarat
type: Organization
subtitle: Collectif
email: nacarat.co@gmail.com
description: Blanc Nacarat Collectif, Artists community
url: https://blancnacarat.github.io
author: Blanc Nacarat
street_address:
city:
state:
zip_code:
country: France
phone:

# homepage tiles
# tiles-source: posts # accepts "posts" or "pages"
# tiles-count: 0

# social settings
soundcloud_url: https://soundcloud.com/blanc-nacarat/
facebook_url: https://www.facebook.com/blanc.nacarat/
twitter_url: https://twitter.com/blancnacarat
instagram_url: https://www.instagram.com/blanc.nacarat/

github_url:
gitlab_url:
googleplus_url:
linkedin_url:
pinterest_url:
slack_url:
500px_url:

# build settings
markdown: kramdown
include: ['.htaccess']

gems:
  - jekyll-font-awesome-sass

font-awesome:
  assets: true

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-seo-tag
  - jekyll-sitemap